
{{- if .Values.config.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "viadee-spring-boot-helm-chart.fullname" . }}
  annotations:
    {{ printf "%s%s%s" "sealedsecrets.bitnami.com/" .Values.config.sealedSecret.mode  ": 'true'"}}
spec:
  encryptedData:
    {{- toYaml .Values.config.sealedSecret.keyEncryptedValuePair | nindent 4 }}
{{- end }}