# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ feat/6-publish-charts ]
  pull_request:
    branches: [ feat/6-publish-charts ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      # Host a Helm charts repo on GitHub Pages
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          # The relative path to the chart-releaser config file
          #config: # optional
          # The charts directory
          charts_dir: . # optional, default is charts
          # The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)
          #charts_repo_url: # optional
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: github.event_name == 'push'
